# Tmux appearance configuration
# ==============================

set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"

set -g @tmux_power_theme 'everforest'
set-option -g status-position top
set-option -g status-style bg=default

