# Tmux keybindings
# ================

# Prevent tmux from clearing selection on mouse release
bind-key -T copy-mode-vi MouseDragEnd1Pane 

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Force kill pane
bind-key x kill-pane

# Force kill window
bind-key X kill-window

# Create new session with prompt
bind-key C command-prompt -p "Enter session name:" "new-session -s '%%'"

# Tmux sessionizer scripts
bind-key -r f run-shell "tmux neww ~/.config/tmux/bin/tmux-sessionizer"
bind-key -r F run-shell "tmux neww ~/.config/tmux/bin/tmux-sshionizer"

# Activate virtual environment
bind v run-shell "tmux send-keys 'source .venv/bin/activate' C-m"

# Reload tmux configuration
bind r source-file ~/.config/tmux/tmux.conf

bind -T copy-mode    MouseDragEnd1Pane send -X clear-selection
bind -T copy-mode-vi MouseDragEnd1Pane send -X clear-selection
